#!/usr/bin/env php
<?php
/*
* This file is part of the Sfynx DDD Generator
*
* (c) Etienne de Longeaux
*
* This source file is subject to the LGPL license that is bundled
* with this source code in the file LICENSE.
*
* version: v2.10.2
*/

function includeIfExists($file)
{
    if (file_exists($file)) {
        return include $file;
    }
}
if (
    (!$loader = includeIfExists(__DIR__.'/../autoload.php'))
    && (!$loader = includeIfExists(__DIR__.'/../../../../../../../../autoload.php'))
    && (!$loader = includeIfExists('/var/www-app/vendor/autoload.php'))
) {
    die(
        'You must set up the project dependencies, run the following commands:'.PHP_EOL.
        'curl -s http://getcomposer.org/installer | php'.PHP_EOL.
        'php composer.phar install'.PHP_EOL
    );
};

(new \Sfynx\CoreBundle\Generator\Application\Application())->run($argv);
